"""Initial migration

Revision ID: e91e32867611
Revises: 
Create Date: 2025-08-26 01:08:20.681649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91e32867611'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('telegram_id', sa.String(), nullable=False),
        sa.Column('steam_id', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('polls',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('chat_id', sa.String(), nullable=True),
        sa.Column('poll_id', sa.String(), nullable=True),
        sa.Column('trigger_time', sa.TIMESTAMP(), nullable=True),
        sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
        sa.Column('trigger_type', sa.String(), nullable=True),
        sa.Column('total_votes', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('poll_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('option_index', sa.Integer(), nullable=True),
        sa.Column('response_time', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('last_activity',
        sa.Column('chat_id', sa.String(), nullable=False),
        sa.Column('last_poll_end', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('chat_settings',
        sa.Column('chat_id', sa.String(), nullable=False),
        sa.Column('poll_time', sa.String(), server_default='15:30', nullable=True),
        sa.Column('chat_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('user_steam_chats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('telegram_id', sa.String(), nullable=True),
        sa.Column('steam_id', sa.String(), nullable=True),
        sa.Column('chat_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_steam_chats')
    op.drop_table('chat_settings')
    op.drop_table('last_activity')
    op.drop_table('votes')
    op.drop_table('polls')
    op.drop_table('users')
    # ### end Alembic commands ###